-- 启用扩展（如果还没启用）
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 插入所有特征数据（包含映射字段）
INSERT INTO features (
    name, code, data_type, unit, description, is_required, validation_rules,
    data_source_id, database_name, table_name, column_name, timestamp_column
) VALUES

-- ============ 温度类 ============
('冷冻水总管供水温度', 'total_chilled_inlet_temp', 'number', '°C', '冷冻水系统总管供水温度', true, '{"min": -50, "max": 150, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai34', 'PointValue', 'UpdateDateTime'),
('冷冻水总管回水温度', 'total_chilled_return_temp', 'number', '°C', '冷冻水系统总管回水温度', true, '{"min": -50, "max": 150, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai35', 'PointValue', 'UpdateDateTime'),
('冷却水总管供水温度', 'total_cooling_inlet_temp', 'number', '°C', '冷却水系统总管供水温度', true, '{"min": -50, "max": 150, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai39', 'PointValue', 'UpdateDateTime'),
('冷却水总管回水温度', 'total_cooling_return_temp', 'number', '°C', '冷却水系统总管回水温度', true, '{"min": -50, "max": 150, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai40', 'PointValue', 'UpdateDateTime'),
('1#主机冷冻水供水温度', 'host_1_chilled_inlet_temp', 'number', '°C', '1号主机冷冻水供水温度', true, '{"min": -50, "max": 150, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai104', 'PointValue', 'UpdateDateTime'),
('1#主机冷冻水回水温度', 'host_1_chilled_return_temp', 'number', '°C', '1号主机冷冻水回水温度', true, '{"min": -50, "max": 150, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai105', 'PointValue', 'UpdateDateTime'),
('1#主机冷却水供水温度', 'host_1_cooling_inlet_temp', 'number', '°C', '1号主机冷却水供水温度', true, '{"min": -50, "max": 150, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai106', 'PointValue', 'UpdateDateTime'),
('1#主机冷却水回水温度', 'host_1_cooling_return_temp', 'number', '°C', '1号主机冷却水回水温度', true, '{"min": -50, "max": 150, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai107', 'PointValue', 'UpdateDateTime'),
('2#主机冷冻水供水温度', 'host_2_chilled_inlet_temp', 'number', '°C', '2号主机冷冻水供水温度', true, '{"min": -50, "max": 150, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai128', 'PointValue', 'UpdateDateTime'),
('2#主机冷冻水回水温度', 'host_2_chilled_return_temp', 'number', '°C', '2号主机冷冻水回水温度', true, '{"min": -50, "max": 150, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai129', 'PointValue', 'UpdateDateTime'),
('2#主机冷却水供水温度', 'host_2_cooling_inlet_temp', 'number', '°C', '2号主机冷却水供水温度', true, '{"min": -50, "max": 150, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai130', 'PointValue', 'UpdateDateTime'),
('2#主机冷却水回水温度', 'host_2_cooling_return_temp', 'number', '°C', '2号主机冷却水回水温度', true, '{"min": -50, "max": 150, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai131', 'PointValue', 'UpdateDateTime'),
('室外温度', 'outdoor_temperature', 'number', '°C', '室外环境温度', true, '{"min": -60, "max": 80, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai31', 'PointValue', 'UpdateDateTime'),
('湿球温度', 'wet_bulb_temperature', 'number', '°C', '室外湿球温度', true, '{"min": -60, "max": 80, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai33', 'PointValue', 'UpdateDateTime'),

-- ============ 压力类 ============
('冷冻水总管供水压力', 'total_chilled_supply_pressure', 'number', 'MPa', '冷冻水系统总管供水压力', true, '{"min": 0, "max": 5, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai36', 'PointValue', 'UpdateDateTime'),
('冷冻水总管回水压力', 'total_chilled_return_pressure', 'number', 'MPa', '冷冻水系统总管回水压力', true, '{"min": 0, "max": 5, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai37', 'PointValue', 'UpdateDateTime'),
('1#主机蒸发器压力', 'host_1_evaporator_pressure', 'number', 'MPa', '1号主机蒸发器压力', true, '{"min": 0, "max": 5, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai111', 'PointValue', 'UpdateDateTime'),
('1#主机冷凝器压力', 'host_1_condenser_pressure', 'number', 'MPa', '1号主机冷凝器压力', true, '{"min": 0, "max": 5, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai110', 'PointValue', 'UpdateDateTime'),
('2#主机蒸发器压力', 'host_2_evaporator_pressure', 'number', 'MPa', '2号主机蒸发器压力', true, '{"min": 0, "max": 5, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai135', 'PointValue', 'UpdateDateTime'),
('2#主机冷凝器压力', 'host_2_condenser_pressure', 'number', 'MPa', '2号主机冷凝器压力', true, '{"min": 0, "max": 5, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai134', 'PointValue', 'UpdateDateTime'),

-- ============ 流量类 ============
('1号冷量计瞬时流量', 'total_1_instantaneous_flow', 'number', 'm³/h', '1号冷量计瞬时流量(1#&2#主机共用)', true, '{"min": 0, "max": 10000, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai178', 'PointValue', 'UpdateDateTime'),

-- ============ 功率类 ============
('主机电表实时总功率', 'total_real_time_power_of_host_meter', 'number', 'kW', '1号主机+2号主机功率', true, '{"min": 0, "max": 5000, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'composite_total_host_meter', 'PointValue', 'UpdateDateTime'),
('冷却塔电表实时总功率', 'total_cooling_tower_real_time_power_of_meter', 'number', 'kW', '1号+2号+3号+4号冷却塔功率', true, '{"min": 0, "max": 5000, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'composite_total_cooling_tower_meter', 'PointValue', 'UpdateDateTime'),
('冷却泵电表实时总功率', 'total_cooling_pump_real_time_power_of_meter', 'number', 'kW', '1号+2号+3号冷却泵功率', true, '{"min": 0, "max": 5000, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'composite_total_cooling_pump_meter', 'PointValue', 'UpdateDateTime'),
('冷冻泵电表实时总功率', 'total_chilled_pump_real_time_power_of_meter', 'number', 'kW', '1号+2号+3号+4号冷冻泵功率', true, '{"min": 0, "max": 5000, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'composite_total_chilled_pump_meter', 'PointValue', 'UpdateDateTime'),
('1#主机电表实时功率', 'real_time_power_of_host_meter_1', 'number', 'kW', '1号主机电表实时功率', true, '{"min": 0, "max": 5000, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai204', 'PointValue', 'UpdateDateTime'),
('2#主机电表实时功率', 'real_time_power_of_host_meter_2', 'number', 'kW', '2号主机电表实时功率', true, '{"min": 0, "max": 5000, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai212', 'PointValue', 'UpdateDateTime'),
('1和2#冷却塔电表实时功率', 'cooling_tower_1_2_power_meter_real_time_power', 'number', 'kW', '1号和2号冷却塔电表实时功率', true, '{"min": 0, "max": 500, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai308', 'PointValue', 'UpdateDateTime'),
('3和4#冷却塔电表实时功率', 'cooling_tower_3_4_power_meter_real_time_power', 'number', 'kW', '3号和4号冷却塔电表实时功率', true, '{"min": 0, "max": 500, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai316', 'PointValue', 'UpdateDateTime'),
('1#冷却泵电表实时功率', 'cooling_pump_1_power_meter_real_time_power', 'number', 'kW', '1号冷却泵电表实时功率', true, '{"min": 0, "max": 500, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai268', 'PointValue', 'UpdateDateTime'),
('2#冷却泵电表实时功率', 'cooling_pump_2_power_meter_real_time_power', 'number', 'kW', '2号冷却泵电表实时功率', true, '{"min": 0, "max": 500, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai276', 'PointValue', 'UpdateDateTime'),
('3#冷却泵电表实时功率', 'cooling_pump_3_power_meter_real_time_power', 'number', 'kW', '3号冷却泵电表实时功率', true, '{"min": 0, "max": 500, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai284', 'PointValue', 'UpdateDateTime'),
('1#冷冻泵电表实时功率', 'chilled_pump_1_power_meter_real_time_power', 'number', 'kW', '1号冷冻泵电表实时功率', true, '{"min": 0, "max": 500, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai228', 'PointValue', 'UpdateDateTime'),
('2#冷冻泵电表实时功率', 'chilled_pump_2_power_meter_real_time_power', 'number', 'kW', '2号冷冻泵电表实时功率', true, '{"min": 0, "max": 500, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai236', 'PointValue', 'UpdateDateTime'),
('3#冷冻泵电表实时功率', 'chilled_pump_3_power_meter_real_time_power', 'number', 'kW', '3号冷冻泵电表实时功率', true, '{"min": 0, "max": 500, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai244', 'PointValue', 'UpdateDateTime'),
('4#冷冻泵电表实时功率', 'chilled_pump_4_power_meter_real_time_power', 'number', 'kW', '4号冷冻泵电表实时功率', true, '{"min": 0, "max": 500, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai252', 'PointValue', 'UpdateDateTime'),

-- ============ 频率类 ============
('1#冷却塔频率反馈', 'cooling_tower_1_frequency_feedback', 'number', 'Hz', '1号冷却塔风机频率反馈', true, '{"min": 0, "max": 100, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai81', 'PointValue', 'UpdateDateTime'),
('1#冷却泵频率反馈', 'cooling_pump_1_frequency_feedback', 'number', 'Hz', '1号冷却泵频率反馈', true, '{"min": 0, "max": 100, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai82', 'PointValue', 'UpdateDateTime'),
('2#冷却泵频率反馈', 'cooling_pump_2_frequency_feedback', 'number', 'Hz', '2号冷却泵频率反馈', true, '{"min": 0, "max": 100, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai83', 'PointValue', 'UpdateDateTime'),
('3#冷却泵频率反馈', 'cooling_pump_3_frequency_feedback', 'number', 'Hz', '3号冷却泵频率反馈', true, '{"min": 0, "max": 100, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai84', 'PointValue', 'UpdateDateTime'),
('1#冷冻泵频率反馈', 'chilled_pump_1_frequency_feedback', 'number', 'Hz', '1号冷冻泵频率反馈', true, '{"min": 0, "max": 100, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai76', 'PointValue', 'UpdateDateTime'),
('2#冷冻泵频率反馈', 'chilled_pump_2_frequency_feedback', 'number', 'Hz', '2号冷冻泵频率反馈', true, '{"min": 0, "max": 100, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai77', 'PointValue', 'UpdateDateTime'),
('3#冷冻泵频率反馈', 'chilled_pump_3_frequency_feedback', 'number', 'Hz', '3号冷冻泵频率反馈', true, '{"min": 0, "max": 100, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai78', 'PointValue', 'UpdateDateTime'),

-- ============ 状态类 ============
('1#主机开关机状态点', 'host_1_running_status', 'boolean', '', '1号主机运行状态', true, '{}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_di42', 'PointValue', 'UpdateDateTime'),
('2#主机开关机状态点', 'host_2_running_status', 'boolean', '', '2号主机运行状态', true, '{}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_di49', 'PointValue', 'UpdateDateTime'),
('1#冷却塔开关机状态点', 'cooling_tower_1_running_status', 'boolean', '', '1号冷却塔运行状态', true, '{}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_di103', 'PointValue', 'UpdateDateTime'),
('2#冷却塔开关机状态点', 'cooling_tower_2_running_status', 'boolean', '', '2号冷却塔运行状态', true, '{}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_di107', 'PointValue', 'UpdateDateTime'),
('3#冷却塔开关机状态点', 'cooling_tower_3_running_status', 'boolean', '', '3号冷却塔运行状态', true, '{}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_di111', 'PointValue', 'UpdateDateTime'),
('4#冷却塔开关机状态点', 'cooling_tower_4_running_status', 'boolean', '', '4号冷却塔运行状态', true, '{}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_di115', 'PointValue', 'UpdateDateTime'),
('1#冷却泵开关机状态点', 'cooling_pump_1_running_status', 'boolean', '', '1号冷却泵运行状态', true, '{}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_di83', 'PointValue', 'UpdateDateTime'),
('2#冷却泵开关机状态点', 'cooling_pump_2_running_status', 'boolean', '', '2号冷却泵运行状态', true, '{}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_di87', 'PointValue', 'UpdateDateTime'),
('3#冷却泵开关机状态点', 'cooling_pump_3_running_status', 'boolean', '', '3号冷却泵运行状态', true, '{}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_di91', 'PointValue', 'UpdateDateTime'),
('4#冷却泵开关机状态点', 'cooling_pump_4_running_status', 'boolean', '', '4号冷却泵运行状态', true, '{}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_di95', 'PointValue', 'UpdateDateTime'),
('1#冷冻泵开关机状态点', 'chilled_pump_1_running_status', 'boolean', '', '1号冷冻泵运行状态', true, '{}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_di63', 'PointValue', 'UpdateDateTime'),
('2#冷冻泵开关机状态点', 'chilled_pump_2_running_status', 'boolean', '', '2号冷冻泵运行状态', true, '{}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_di67', 'PointValue', 'UpdateDateTime'),
('3#冷冻泵开关机状态点', 'chilled_pump_3_running_status', 'boolean', '', '3号冷冻泵运行状态', true, '{}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_di71', 'PointValue', 'UpdateDateTime'),
('4#冷冻泵开关机状态点', 'chilled_pump_4_running_status', 'boolean', '', '4号冷冻泵运行状态', true, '{}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_di75', 'PointValue', 'UpdateDateTime'),

-- ============ 冷量与性能类 ============
('1号冷量计实时冷量', 'instant_cooling_capacity', 'number', 'kW', '1号冷量计测量的瞬时冷量', true, '{"min": 0, "max": 50000, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai180', 'PointValue', 'UpdateDateTime'),
 ('累计冷量','cumulative_cooling_capacity','number','kWh','累计冷量（来自 xmhf_zlz2_ai181）',true,'{"min": 0, "max": 9999999, "precision": 2}'::jsonb,
1,'xmhf_hisdata','xmhf_zlz2_ai181','PointValue','UpdateDateTime'),
('每小时用冷量', 'hourly_cooling_energy', 'number', 'kWh', '通过累计冷量整点差值计算的每小时冷量消耗，代表过去一小时的用冷量（例如16:00的值对应15:00–16:00的冷量）', true, '{"min": 0, "max": 50000, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'composite_hourly_cooling_energy', 'PointValue', 'UpdateDateTime'),
('主机COP', 'coefficient_of_performance', 'number', '', '主机性能系数', true, '{"min": 0, "max": 20, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'composite_cop1', 'PointValue', 'UpdateDateTime'),
('系统散热量', 'system_heat_dissipation', 'number', 'kW', '系统总散热量', true, '{"min": 0, "max": 50000, "precision": 2}'::jsonb,
 1, 'xmhf_hisdata', 'composite_system_heat_dissipation', 'PointValue', 'UpdateDateTime'),

-- ============ 环境类 ============
('室外湿度', 'outdoor_humidity', 'number', '%', '室外环境相对湿度', true, '{"min": 0, "max": 100, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai32', 'PointValue', 'UpdateDateTime'),

-- ============ 新增温差特征 ============
('冷却水供回水温差', 'cooling_water_temp_diff', 'number', '°C', '冷却水供回水温差', true, '{"min": -50, "max": 50, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai49', 'PointValue', 'UpdateDateTime'),
('冷冻水供回水温差', 'chilled_water_temp_diff', 'number', '°C', '冷冻水供回水温差', true, '{"min": -50, "max": 50, "precision": 1}'::jsonb,
 1, 'xmhf_hisdata', 'xmhf_zlz2_ai47', 'PointValue', 'UpdateDateTime')

ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    data_type = EXCLUDED.data_type,
    unit = EXCLUDED.unit,
    description = EXCLUDED.description,
    is_required = EXCLUDED.is_required,
    validation_rules = EXCLUDED.validation_rules,
    data_source_id = EXCLUDED.data_source_id,
    database_name = EXCLUDED.database_name,
    table_name = EXCLUDED.table_name,
    column_name = EXCLUDED.column_name,
    timestamp_column = EXCLUDED.timestamp_column,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO features (
    name, code, data_type, unit, description, is_required, validation_rules,
    data_source_id, database_name, table_name, column_name, timestamp_column
) VALUES (
    '每小时用冷量',
    'hourly_cooling_energy',
    'number',
    'kWh',
    '通过累计冷量整点差值计算的每小时冷量消耗，代表过去一小时的用冷量（例如16:00的值对应15:00–16:00的冷量）',
    true,
    '{"min": 0, "max": 50000, "precision": 2}'::jsonb,
    1,
    'xmhf_hisdata',
    'composite_hourly_cooling_energy',
    'PointValue',
    'UpdateDateTime'
)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    data_type = EXCLUDED.data_type,
    unit = EXCLUDED.unit,
    description = EXCLUDED.description,
    is_required = EXCLUDED.is_required,
    validation_rules = EXCLUDED.validation_rules,
    data_source_id = EXCLUDED.data_source_id,
    database_name = EXCLUDED.database_name,
    table_name = EXCLUDED.table_name,
    column_name = EXCLUDED.column_name,
    timestamp_column = EXCLUDED.timestamp_column,
    updated_at = CURRENT_TIMESTAMP;

